networks:
  eth_network:
    name: ethereum_network
    driver: bridge

services:
  # Ethereum Execution Layer (Reth)
  reth:
    image: ghcr.io/paradigmxyz/reth
    container_name: reth
    restart: unless-stopped
    ports:
      - "8545:8545"         # HTTP
      - "8546:8546"         # WebSocket
      - "30303:30303"       # P2P TCP
      - "30303:30303/udp"   # P2P UDP
      - "8551:8551"         # Engine API
    volumes:
      - ./data/reth:/root/.reth
      - ./jwt-secret.txt:/jwt-secret.txt:ro
    command:
      - node
      - --datadir=/root/.reth
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,miner,mev
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,miner,mev
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/jwt-secret.txt
      - --bootnodes=enode://87a32fd13bd596b2ffca97020e31aef4ddcc1bbd4b95bb633d16c1329f654f34049ed240a36b449fda5e5225d70fe40bc667f53c304b71f8e68fc9d448690b51@3.231.138.188:30301,enode://ca21ea8f176adb2e229ce2d700830c844af0ea941a1d8152a9513b966fe525e809c3a6c73a2c18a12b74ed6ec4380edf91662778fe0b79f6a591236e49e176f9@184.72.129.189:30301,enode://acf4507a211ba7c1e52cdf4eef62cdc3c32e7c9c47998954f7ba024026f9a6b2150cd3f0b734d9c78e507ab70d59ba61dfe5c45e1078c7ad0775fb251d7735a2@3.220.145.177:30301,enode://8a5a5006159bf079d06a04e5eceab2a1ce6e0f721875b2a9c96905336219dbe14203d38f70f3754686a6324f786c2f9852d8c0dd3adac2d080f4db35efc678c5@3.231.11.52:30301,enode://cdadbe835308ad3557f9a1de8db411da1a260a98f8421d62da90e71da66e55e98aaa8e90aa7ce01b408a54e4bd2253d701218081ded3dbe5efbbc7b41d7cef79@54.198.153.150:30301
    networks:
      eth_network:
        aliases:
          - reth

  # Ethereum Consensus Layer (Lighthouse)
  lighthouse:
    image: sigp/lighthouse:latest
    container_name: ethereum-lighthouse
    restart: unless-stopped
    ports:
      - "9001:9001"         # P2P TCP
      - "9001:9001/udp"     # P2P UDP
      - "5052:5052"         # HTTP API
      - "5053:5053"         # Metrics
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./jwt-secret.txt:/jwt-secret.txt:ro
    command:
      - lighthouse
      - beacon_node
      - --execution-endpoint=http://reth:8551
      - --execution-jwt=/jwt-secret.txt
      - --enr-address=170.55.104.206
      - --enr-udp-port=9001
      - --enr-tcp-port=9001
      - --http
      - --http-address=0.0.0.0
      - --port=9001
      - --discovery-port=9001
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5053
      - --checkpoint-sync-url=https://mainnet-checkpoint-sync.attestant.io
      - --target-peers=200
      - --network=mainnet
      - --disable-packet-filter
    depends_on:
      - reth
    networks:
      eth_network:
        aliases:
          - lighthouse